name: "Run latexmk"
on:
    create:
        tags:
            - v*
jobs:
    latexmk:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
              # Nix Flakes doesn't work on shallow clones
              fetch-depth: 0
        - uses: cachix/install-nix-action@v11
          with:
            install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
            extra_nix_config: |
              experimental-features = nix-command flakes
        - run: nix build
        - uses: actions/upload-artifact@v2
          with:
            name: ms-thesis.pdf
            path: ./result
